spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: superpostgres
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    topic:
      finish-registration: finish-registration
      create-documents: create-documents
      send-documents: send-documents
      send-ses: send-ses
      credit-issued: credit-issued
      application-denied: application-denied
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8090