spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8085


feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000