spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: kafka:9092

  mail:
    host: smtp.yandex.com
    port: 587
    username: zeevvsss@yandex.ru
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.yandex.com

mail:
  sender: zeevvsss@yandex.ru

server:
  port: 8081