name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build Application with Maven
        working-directory: ./application
        run: mvn -B clean install --file pom.xml

      - name: Build Conveyor with Maven
        working-directory: ./conveyor
        run: mvn -B clean install --file pom.xml

      - name: Build Deal with Maven
        working-directory: ./deal
        run: mvn -B clean install --file pom.xml

      - name: Build Dossier with Maven
        working-directory: ./dossier
        run: mvn -B clean install --file pom.xml

      - name: Build Gateway with Maven
        working-directory: ./gateway
        run: mvn -B clean install --file pom.xml

  tests-covarage:
    defaults:
      run:
        working-directory: ./application
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Test Coverage
        uses: codecov/codecov-action@v3