name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build Application with Maven
        working-directory: ./application
        run: mvn -B clean install --file pom.xml

      - name: Build Conveyor with Maven
        working-directory: ./conveyor
        run: mvn -B clean install --file pom.xml

      - name: Build Deal with Maven
        working-directory: ./deal
        run: mvn -B clean install --file pom.xml

      - name: Build Dossier with Maven
        working-directory: ./dossier
        run: mvn -B clean install --file pom.xml

      - name: Build Gateway with Maven
        working-directory: ./gateway
        run: mvn -B clean install --file pom.xml

  tests-covarage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11


      - name: Maven Verify Application
        working-directory: ./application
        run: mvn -B clean verify

      - name: Test Coverage Application
        uses: codecov/codecov-action@v3
        with:
          directory: ./application
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Application


      - name: Maven Verify Conveyor
        working-directory: ./conveyor
        run: mvn -B clean verify

      - name: Test Coverage Conveyor
        uses: codecov/codecov-action@v3
        with:
          directory: ./conveyor
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Conveyor


      - name: Maven Verify Deal
        working-directory: ./deal
        run: mvn -B clean verify

      - name: Test Coverage Deal
        uses: codecov/codecov-action@v3
        with:
          directory: ./deal
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Deal


      - name: Maven Verify Dossier
        working-directory: ./dossier
        run: mvn -B clean verify

      - name: Test Coverage Dossier
        uses: codecov/codecov-action@v3
        with:
          directory: ./dossier
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Dossier


      - name: Maven Verify Gateway
        working-directory: ./gateway
        run: mvn -B clean verify

      - name: Test Coverage Gateway
        uses: codecov/codecov-action@v3
        with:
          directory: ./gateway
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Gateway

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Analyze Application with SonarCloud Application
        working-directory: ./application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=semenovrustam_Credit_Conveyor


      - name: Analyze Conveyor with SonarCloud
        working-directory: ./conveyor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=semenovrustam_Credit_Conveyor


      - name: Analyze Deal with SonarCloud
        working-directory: ./deal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=semenovrustam_Credit_Conveyor


      - name: Analyze Dossier with SonarCloud
        working-directory: ./dossier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=semenovrustam_Credit_Conveyor


      - name: Analyze Gateway with SonarCloud
        working-directory: ./gateway
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=semenovrustam_Credit_Conveyor